<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c54f38e9-d541-4d0c-9634-02e26e5810e2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fintrack.Application\Fintrack.Application.csproj" />
    <ProjectReference Include="..\Fintrack.Infrastructure\Fintrack.Infrastructure.csproj" />
  </ItemGroup>

</Project>
